version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qzwxec123
    ports:
      - 5432:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d